### PR TITLE
Specify columns in copy from S3

### PR DESCRIPTION
**Pull request by aheyman11**
Specify column list in the copy command from S3 to Redshift. This allows static sources to possibly have extra columns (to the right) not loaded by Arthur.

I couldn't add a type annotation to `relation` in `copy_from_uri` because importing `LoadableRelation` would introduce circular dependencies.

### CODE REVIEW

**Comment by bhtucker** [comment]
LGTM

**Comment by bhtucker** [comment]
I'll confess that I argued for passing the relation rather than those two arguments.

What about a base class defined in `relation.py` that both `RelationDescription` and `LoadableRelation` can extend? Even if they aren't extending each other, would be good to show they are the same 'type'

**Comment by tvogels01** [comment]
Well, I'm not writing Java for a reason ;-)  (That being said, having interfaces would be nice at times.)

There are cases in the code already where we're staying away from relation descriptions, e.g when they are built. Having the pieces (table name and columns) matches this pattern. None of the modules inside `etl.design` need relation descriptions.  Why should `etl.design.redshift`?

**Comment by tvogels01** [comment]
We should merge this along with PR #61 into a new version (v1.6.1?)

**Pull request merged**
