### PR TITLE
Show component (and error) of pipeline

### PR DESCRIPTION
**Pull request by tvogels01**
Update `show_pipelines` to see details of a pipeline. It makes watching paint dry more fun.

In case you're wondering what information about a data pipeline is available, try out the new `--as-json` option,
which will then dump all that information in JSON-format. Be careful here: running this without selecting
a pipeline (or a few like `df-0*`) will take a bit of time.

Since the error messages are now shown here, we remove the "cancellation reason" and "error stacktrace" from the SNS messages. (They were usually NULL anyways.)

For example:
```
$ arthur.py show_pipelines -q 'df-0712345BLABCDCHNQUF'
Pipeline ID            | Name                                                          | Health  | State
-----------------------+---------------------------------------------------------------+---------+----------
df-0712345BLABCDCHNQUF | ETL Pizza Loader Pipeline (development @ 2021-02-07T13:41:38) | HEALTHY | SCHEDULED
(1 row)

Key                      | Value
-------------------------+-----------------------
@creationTime            | 2021-02-07T13:41:41
@healthStatus            | HEALTHY
@healthStatusUpdatedTime | 2021-02-07T13:43:55
@id                      | df-0712345BLABCDCHNQUF
@lastActivationTime      | 2021-02-07T13:41:44
@latestRunTime           | 2021-02-07T13:41:38
@pipelineState           | SCHEDULED
@scheduledEndTime        | 2021-02-08T13:41:38
@scheduledStartTime      | 2021-02-07T13:41:38
uniqueId                 | dw-etl-pizza-pipeline
(10 rows)

Instance Name                                          | Type                 | Status                  | Actual Start Time   | Actual End Time
-------------------------------------------------------+----------------------+-------------------------+---------------------+--------------------
@Copy Bootstrap (EC2)_2021-02-07T13:41:38              | ShellCommandActivity | FINISHED                | 2021-02-07T13:41:47 | 2021-02-07T13:43:55
@Bootstrap (EC2)_2021-02-07T13:41:38                   | ShellCommandActivity | FINISHED                | 2021-02-07T13:41:47 | 2021-02-07T13:44:24
@Arthur Upgrade (EC2)_2021-02-07T13:41:38              | ShellCommandActivity | RUNNING                 | 2021-02-07T13:41:47 | ---
@ArthurDriverEC2Resource_2021-02-07T13:41:38           | Ec2Resource          | RUNNING                 | 2021-02-07T13:41:47 | ---
@Arthur Promote (EC2)_2021-02-07T13:41:38              | ShellCommandActivity | WAITING_ON_DEPENDENCIES | 2021-02-07T13:41:47 | ---
@Arthur Terminate Sessions (EC2)_2021-02-07T13:41:38   | ShellCommandActivity | WAITING_ON_DEPENDENCIES | 2021-02-07T13:41:47 | ---
@Arthur Unload (EC2)_2021-02-07T13:41:38               | ShellCommandActivity | WAITING_ON_DEPENDENCIES | 2021-02-07T13:41:47 | ---
@Publish and Backup (EC2)_2021-02-07T13:41:38          | ShellCommandActivity | WAITING_ON_DEPENDENCIES | 2021-02-07T13:41:47 | ---
@Send Health Check After ETL (EC2)_2021-02-07T13:41:38 | ShellCommandActivity | WAITING_ON_DEPENDENCIES | 2021-02-07T13:41:47 | ---
(9 rows)
```

One use case for the JSON-formatted output is to look for configuration. E.g. to find the pipeline parameters:
```shell
arthur.py show_pipelines --as-json  | jq  '.pipelines[] | [map(.objects.component)[]."@Parameters".string_values]'
```

### CODE REVIEW

**Comment by soumyadsanyal** [comment]
On 

```
:arthur-redshift-etl soumya.sanyal$ bin/docker_build.sh 
```

```
Installing run_tests.py script to /opt/local/redshift_etl/venv/bin

Installed /opt/local/redshift_etl/venv/lib/python3.7/site-packages/redshift_etl-1.37.0-py3.7.egg
Processing dependencies for redshift-etl==1.37.0
Finished processing dependencies for redshift-etl==1.37.0
Traceback (most recent call last):
  File "/opt/local/redshift_etl/venv/bin/arthur.py", line 11, in <module>
    load_entry_point('redshift-etl==1.37.0', 'console_scripts', 'arthur.py')()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.37.0-py3.7.egg/etl/commands.py", line 35, in <module>
    import etl.pipeline
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.37.0-py3.7.egg/etl/pipeline.py", line 63, in <module>
    class DataPipeline:
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.37.0-py3.7.egg/etl/pipeline.py", line 64, in DataPipeline
    client = boto3.client("datapipeline")
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
The command '/bin/sh -c source "/opt/local/$PROJ_NAME/venv/bin/activate" &&     python3 setup.py install &&     rm -rf build dist &&     arthur.py --version' returned a non-zero code: 1
```

**Comment by tvogels01** [comment]
Oh. That's on a different PR. (Setting a default for testing.)

But sadly there's also a bug ... this would show all components, not just from the latest run.

**Comment by soumyadsanyal** [comment]
Gettin this on build -- should I be passing `region` from the command line?

```
:arthur-redshift-etl soumya.sanyal$ git checkout show-component-of-pipeline
Branch 'show-component-of-pipeline' set up to track remote branch 'show-component-of-pipeline' from 'origin'.
Switched to a new branch 'show-component-of-pipeline'

:arthur-redshift-etl soumya.sanyal$ git pull
Already up to date.


:arthur-redshift-etl soumya.sanyal$ bin/build_arthur.sh 
+ cd /Users/soumya.sanyal/code/arthur-redshift-etl
+ test -f Dockerfile
+ bin/release_version.sh
Release information is unchanged.
toplevel=/Users/soumya.sanyal/code/arthur-redshift-etl
commit=03bcefcd4cf10f3e278c0175c0364117607acba2 (show-component-of-pipeline)
date=2021-02-27 09:21:11 -0500
+ docker build --tag arthur-redshift-etl:latest .
Sending build context to Docker daemon  888.3kB
Step 1/17 : FROM amazonlinux:2.0.20201218.1
 ---> 9917dfe117ca
Step 2/17 : ARG PROJ_NAME=redshift_etl
 ---> Using cache
 ---> ade7e5effd8f
Step 3/17 : RUN yum install -y         awscli         jq         libyaml-devel         openssh-clients         postgresql         procps-ng         python3         python3-devel         tmux         vim-minimal
 ---> Using cache
 ---> 7e1c9103cf20
Step 4/17 : RUN useradd --comment 'Arthur ETL' --user-group --create-home arthur &&     mkdir --parent /opt/data-warehouse "/opt/local/$PROJ_NAME" /opt/src/arthur-redshift-etl &&     chown -R arthur.arthur /opt/*
 ---> Using cache
 ---> cb0acdac350b
Step 5/17 : USER arthur
 ---> Using cache
 ---> 6d32e4773516
Step 6/17 : COPY --chown=arthur:arthur etc/.bash_history etc/.bashrc etc/.bash_profile /home/arthur/
 ---> Using cache
 ---> 55fb926a0d47
Step 7/17 : COPY --chown=arthur:arthur     bin/release_version.sh bin/send_health_check.sh bin/sync_env.sh bin/upload_env.sh     "/opt/local/$PROJ_NAME/bin/"
 ---> Using cache
 ---> ee365483e507
Step 8/17 : COPY requirements*.txt /tmp/
 ---> Using cache
 ---> a24c8f6925ad
Step 9/17 : RUN python3 -m venv "/opt/local/$PROJ_NAME/venv" &&     source "/opt/local/$PROJ_NAME/venv/bin/activate" &&     python3 -m pip install --upgrade pip==20.3.4 --disable-pip-version-check --no-cache-dir &&     python3 -m pip install --requirement /tmp/requirements-dev.txt --disable-pip-version-check --no-cache-dir
 ---> Using cache
 ---> 021b324bb0be
Step 10/17 : RUN echo '# Format to set password (used by create_user and update_user): *:5439:*:<user>:<password>' > /home/arthur/.pgpass     && chmod go= /home/arthur/.pgpass
 ---> Using cache
 ---> 35eeba1b01d7
Step 11/17 : WORKDIR /opt/src/arthur-redshift-etl
 ---> Using cache
 ---> c9de85f4cd5b
Step 12/17 : COPY --chown=arthur:arthur ./ ./
 ---> 5fe98518f204
Step 13/17 : RUN source "/opt/local/$PROJ_NAME/venv/bin/activate" &&     python3 setup.py install &&     rm -rf build dist &&     arthur.py --version
 ---> Running in 40efe9e0017f
running install

...


Installed /opt/local/redshift_etl/venv/lib/python3.7/site-packages/redshift_etl-1.39.0-py3.7.egg
Processing dependencies for redshift-etl==1.39.0
Finished processing dependencies for redshift-etl==1.39.0
Traceback (most recent call last):
  File "/opt/local/redshift_etl/venv/bin/arthur.py", line 11, in <module>
    load_entry_point('redshift-etl==1.39.0', 'console_scripts', 'arthur.py')()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.39.0-py3.7.egg/etl/commands.py", line 35, in <module>
    import etl.pipeline
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.39.0-py3.7.egg/etl/pipeline.py", line 93, in <module>
    class DataPipeline:
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/redshift_etl-1.39.0-py3.7.egg/etl/pipeline.py", line 94, in DataPipeline
    client = boto3.client("datapipeline")
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/opt/local/redshift_etl/venv/lib64/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
The command '/bin/sh -c source "/opt/local/$PROJ_NAME/venv/bin/activate" &&     python3 setup.py install &&     rm -rf build dist &&     arthur.py --version' returned a non-zero code: 1
```

**Comment by tvogels01** [comment]
@soumyadsanyal I can't tell why this is happening to you.

I'd suggest to follow our standard documentation and set:
```
export AWS_DEFAULT_PROFILE=<use appropriate value>
```

**Comment by tvogels01** [comment]
I've added `AWS_DEFAULT_REGION` setting in the Docker image now so that this should not longer be an issue.

**Review by soumyadsanyal — APPROVED** [review]
👍

**Pull request merged**
